const UserActionTypes = {
  USER_FETCH: 'USER_FETCH',
  USER_SUCCESS: 'USER_SUCCESS',
  USER_FAIL: 'USER_FAIL',
  USER_TESTS_FETCH: 'USER_TESTS_FETCH',
  USER_TESTS_SUCCESS: 'USER_TESTS_SUCCESS',
  USER_TESTS_FAIL: 'USER_TESTS_FAIL',
  USER_TEST_HISTORY_FETCH: 'USER_TEST_HISTORY_FETCH',
  USER_TEST_HISTORY_SUCCESS: 'USER_TEST_HISTORY_SUCCESS',
  USER_TEST_HISTORY_FAIL: 'USER_TEST_HISTORY_FAIL',
  USER_CARDS_FETCH: 'USER_CARDS_FETCH',
  USER_CARDS_SUCCESS: 'USER_CARDS_SUCCESS',
  USER_CARDS_FAIL: 'USER_CARDS_FAIL',
};

export default UserActionTypes;
